#!/bin/bash
mount_point=/mnt
cleanup()
{
	set +e
	sync
	umount ${mount_point}
}

trap cleanup INT TERM EXIT

set -e
user=tomek
group=tomek
target_dir=`make echo-build-root`
input=floppy-template.img
output=${target_dir}floppy.img 
install -g ${group} -o ${user} -m664 $input $output
mount -o loop $output ${mount_point}
cp ${target_dir}image ${mount_point}/boot/kernel
cp ${target_dir}image ${mount_point}/kernel
